### ISSUE TITLE
Playback stopping after few minutes

### ISSUE THREAD

**Issue by acolombier** [sshmanko/acestream-armv7#1]
Hi,

I'm experiencing issues after fews minutes playing, the playback suddenly stops. Following the logs, it seems the segmenter is the one causing problem following of the duration of the last segment.

I'm running Plexus on OpenELEC with a RPI 3, but the results were similar on LibreELEC

Here are the logs:
[segmenter.log](https://github.com/sshmanko/acestream-armv7/files/1963163/segmenter.log)
[kodi.log](https://github.com/sshmanko/acestream-armv7/files/1963164/kodi.log)
[acestream.log](https://github.com/sshmanko/acestream-armv7/files/1963165/acestream.log)

**Comment by sshmanko** [comment]
I am running latest version (3.1.24) on RPI 3 as well, with OSMC distro and experience no such issues.
I can suggest to try different video source for a start. 

Also make sure your pi has enough:
1) Available memory
2) Disk space
3) Network bandwidth

I see there is newer 3.1.28 version on official website so I will try to make new release in a few days

**Comment by acolombier** [comment]
Hi,

Thank you for you reply.

I found the release 3.1.30 on a Russian website, and it seems the sudden drop doesn't happen anymore. I can PR it if you want?

However, I still experience some weird screwed frames from time to time (that I doesn't experience on a laptop with the same stream) although RAM, bandwidth, storage don't look overloaded

**Comment by sshmanko** [comment]
I also see green pixels on some HD broadcasts, however I am not sure if the reason is engine version - seems more than bandwidth/peer issues. SD broadcasts are always fine (on 50Mbit connection)
You can test previous releases to see if it fixes your issue, as engine code is closed there is not much I can do here unfortunately. (Personally I just bought latest Intel NUC and will soon be migrating to Windows powered HTPC)

**Comment by mariofenech** [comment]
I tried all 3.1.24,3.1.28  and they both had the issue of playback suddenly stops....it seems that 3.1.30 is working fine with some small changes in settings...seemed that caching to ram was using too much ram with the default 20 seconds buffer I had on mine..rpi2-libreelec..
Now I m set to 5s buffer....100mb max use of ram for acestream and stream set to original output..and no issues so far...smooth as butter...hope it stays like this..
