### ISSUE TITLE
Dual Audio No Option Available..only Russian

### ISSUE THREAD

**Issue by mariofenech** [sshmanko/acestream-armv7#2]
Hi
I m trying the latest version 3.1.30 on Rpi 2 running libreelec..
Issue is I have no option for dual audio channels when I play a stream through plexus addon..

When I play a stream direct in playlist http://127.0.0.1:6878/ace/getstream?url=etc
the dual audio is avaliable..

thanks

**Comment by sshmanko** [comment]
AFAIK plexus addon is no longer maintained and this issue is not acestream engine bug, if you able to select language in different player.

**Comment by mariofenech** [comment]
It's not an acestream bug...it's an acestream setting I have no idea how to change...
I just found out that if the live tv setting of acestream engine is changed from auto/http to original the option of dual audio is there in plexus...
Should the webui be working on your version...might be able to change setting from there..or you know of any other way to change output stream to original manually?

**Comment by sshmanko** [comment]
Engine settings can be changed in WebUI here:
http://\<IP\>:6878/webui/app/ReplaceMe/server#proxy-server-settings

**Comment by mariofenech** [comment]
Ok working fine now...dual audio also available..also managed to edit another acestream addon using your acestream 3.1.30 and can now change settings of acestream directly from Libreelec..thanks

**Comment by sshmanko** [comment]
great, thanks for the feedback
can you share the addon name you are using with acestream engine as it might be useful for others experiencing similar issues?

**Comment by mariofenech** [comment]
Yeah no problem..
This addon you can play with acestream settings directly from kodi...it's a service addon so you wont see it in program addons...you ll need to go to addons->service addons and configure from there....
It will start acestream as a system service in system.d no need to enable service..it's all done automatically...also you can cache to any usb device instead of memory all through the addon settings...
I m running your 3.1.30 with this and working fine...just replaced androidfs and system folder with your version..
I'm using 1.0.5 [https://github.com/lysyiklad/repokodi/tree/master/service.system.acestreammedia](url)

**Comment by mariofenech** [comment]
Well I'v spent some time setting up Noxbit on Rpi and 1st day of testing it looks rock solid..might be a better alternative to acestreams altough not much info around...ram is very low compared to acestreams even when caching acestream to usb storage...Still not sure where noxbit is caching.... 
Noxbit also has proxy builtin so can be installed on any computer in the house and serving your rpi libreelec but it really doesnt use much resources on the rpi...

**Comment by mariofenech** [comment]
ACE Stream Media (LibreELEC ARM) from https://github.com/seppius-xbmc-repo/ru/tree/master/repository.search.db
