### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by atomoc** [sshmanko/acestream-armv7#8]
Files downloaded in this way are not played, giving errors.

**Comment by sshmanko** [comment]
does web-ui work? 
http://<IP>:6878/webui/api/service?method=get_version&format=jsonp&callback=mycallback

**Comment by atomoc** [comment]
`mycallback({"result": {"code": 3013300, "platform": "android", "version": "3.1.33"}, "error": null});`

**Comment by sshmanko** [comment]
значит сервис стартует и работает, а как вы пытаетесь его использовать? проблема видимо в интеграции с плеером

**Comment by atomoc** [comment]
Спасибо за поддержку, молниеносную. Вроде бы сейчас работает, быстро поднял ещё раз, позавчера пытался, что то было не так. Запускал вроде через /opt/acestream/acestream.start и сервисом, сейчас через /opt/acestream/acestream.start работает. Попробую через сервис и закрою задачу, если всё будет ок.

**Comment by atomoc** [comment]
Не успел, зависло, оказывается это было поток скачанный посредством docker aaaler/acestream-pi. Теперь как и раньше, запускается скачивание, и как доходит до открытия коди пишет: Воспроизведение прервано, загляните в логи

**Comment by atomoc** [comment]
Но в корне пользователя логи за вчерашний день только, да и в журнале самой проги только что успешно запущено kodi.

**Comment by sshmanko** [comment]
процесс acestream из этого репозитория остается в памяти или вылетает?
Порт посмотрите что бы совпадал 8621 вроде должен быть (сейчас нет распберри под рукой проверить, netstat -tulpan | grep acestream)

**Comment by atomoc** [comment]
По netstat -tulpan | grep acestream ничего не выводится, /opt/acestream/acestream.start висит и в http://:6878/webui/api/service?method=get_version&format=jsonp&callback=mycallback так же выводятся данные

**Comment by atomoc** [comment]
Есть ещё такое:
![2019-02-22 15-16-15](https://user-images.githubusercontent.com/465108/53242102-dcec5600-36b4-11e9-84a3-43effcedb57a.png)

**Comment by sshmanko** [comment]
отлично, процесс работает, проблема или в конфигурации коди или в стриме

**Comment by atomoc** [comment]
Если в коди, то почему через aaaler/acestream-pi пашет...

**Comment by sshmanko** [comment]
так там порт 62062, а тут 8621

**Comment by atomoc** [comment]
Поменял в настройках клиентского плагина порт на 8621 и теперь даже не качает: Ждём ответа

**Comment by sshmanko** [comment]
рестарт попробуйте системы, потом запуск сервиса через acestream.start, запуск Kodi и попробуйте еще раз

**Comment by atomoc** [comment]
Делаю

**Comment by atomoc** [comment]
Тоже самое, пробовал сервер менять с 127.0.0.1 на 0.0.0.0 - бестолку

**Comment by atomoc** [comment]
Почему на порту 62062 такое поведение? Скачивание и в конце облом

**Comment by sshmanko** [comment]
попробуйте другой плагин к коди и/или стримы.
Сам тестировал на torrent-tv и https://github.com/tvaddonsco/program.plexus

**Comment by atomoc** [comment]
А что такое стримы? Их я точно не менял

**Comment by sshmanko** [comment]
Так ссылки на каналы вы откуда берете? Можно тут посмотреть: https://acestreamid.com/
Можно с помойки: http://91.92.66.82/trash/ttv-list/

**Comment by atomoc** [comment]
Ясно, я с плагина rutracker torrent-tv и lostfilm их беру

**Comment by atomoc** [comment]
Другого плагина нет, есть только разные версии текущего, одна хуже другой...

**Comment by atomoc** [comment]
Кое что нашёл:
![2019-02-22 15-44-34](https://user-images.githubusercontent.com/465108/53243409-cc3ddf00-36b8-11e9-9041-c075a6b8d2d1.png)
Это при запущенном aaaler/acestream-pi, везде 127.0.0.1, в вашем же сервисе указывается ip локальной сети. Может что то в /etc/hosts внести?

**Comment by atomoc** [comment]
И почему в вашем не используется обычный 62062? Об этом не указано даже в READMY

**Comment by sshmanko** [comment]
эта версия слушает на всех адресах системы - 0.0.0.0
Проверить открыт порт или нет можно командой `telnet 127.0.0.1 8621`

раз webui показывает версию значит все ок с сервисом. Порт 8621 это как раз стандартный для acestream

Можете попробовать вот такой плагин:
https://youtu.be/hhnFQ8XI91A?t=239

**Comment by sshmanko** [comment]
да порт наверное стоит добавить в README

**Comment by atomoc** [comment]
Если речь идёт о plexus то там тоже самое на порту 8621: Avaiting response

**Comment by sshmanko** [comment]
`telnet 127.0.0.1 8621` показывает Connected to 127.0.0.1.
Escape character is '^]' ?

**Comment by atomoc** [comment]
Да. На стандартном порту, который и в плексусе указан, 62062, пишет Torrent not available or invalid, хотя файл только скачан с kinozal

**Comment by sshmanko** [comment]
надо указать в настройках плексуса порт 8621 и перезапустить Kodi
потом можно попробовать открыть поток через Plexus по ID, например:
2b93b00cc5a5bf6535609228f0167d5c0ef2fb60

**Comment by atomoc** [comment]
Пишет: Connecting

**Comment by sshmanko** [comment]
А из консоли:
`telnet 127.0.0.1 8621`

**Comment by atomoc** [comment]
Не понял последнего сообщения, я же написал что пишет Connected to 127.0.0.1

**Comment by sshmanko** [comment]
хорошо, а в Plexus открыть по Acestream ID ?

**Comment by sergey-zabolotny** [comment]
у меня не стартует в докер контейнере.
`docker logs ace-engine-3.1.33
+ PATH=/sbin:/bin:/usr/sbin:/usr/bin
+ dirname /opt/acestream/acestream.start
+ readlink -f /opt/acestream
+ ACEADDON=/opt/acestream
+ ACECHROOT=androidfs
+ mount
+ grep -E '( /opt/acestream/androidfs/proc | /opt/acestream/androidfs/sys | /opt/acestream/androidfs/dev )'
+ mkdir -p /opt/acestream/androidfs/system
+ mkdir -p /opt/acestream/androidfs/storage
+ mkdir -p /opt/acestream/androidfs/dev
+ mkdir -p /opt/acestream/androidfs/proc
+ mkdir -p /opt/acestream/androidfs/sys
+ mkdir -p /opt/acestream/androidfs/system/etc
+ '[' '!' -f /opt/acestream/androidfs/system/etc/resolv.conf ]
+ cp -L /etc/resolv.conf /opt/acestream/androidfs/system/etc/resolv.conf
+ '[' '!' -f /opt/acestream/androidfs/system/etc/hosts ]
+ cp -L /etc/hosts /opt/acestream/androidfs/system/etc/hosts
+ echo '67.215.246.10 router.bittorrent.com'
+ echo '212.129.33.59 dht.transmissionbt.com'
+ echo '82.221.103.244 router.utorrent.com'
+ mount -o bind /dev /opt/acestream/androidfs/dev
+ mount -t proc proc /opt/acestream/androidfs/proc
+ mount -t sysfs sysfs /opt/acestream/androidfs/sys
+ chown -R root:root /opt/acestream/androidfs/system
+ find /opt/acestream/androidfs/system -type d -exec chmod 755 '{}' ';'
+ find /opt/acestream/androidfs/system -type f -exec chmod 644 '{}' ';'
+ chmod 755 /opt/acestream/androidfs/system/bin/acestream.sh /opt/acestream/androidfs/system/bin/busybox /opt/acestream/androidfs/system/bin/linker /opt/acestream/androidfs/acestream.engine/python/bin/python
+ chroot /opt/acestream/androidfs /system/bin/busybox sh -c /system/bin/acestream.sh
chroot: can't execute '/system/bin/busybox': Exec format error
`
докер файл такой:

`
FROM alpine:3.9
USER root

RUN set -ex; \
    apk add --update --no-cache \
	bash

COPY v3.1.33/ /opt/acestream/

EXPOSE 62062

CMD ["/opt/acestream/acestream.start"]
`

все из репы лежит в папке v3.1.33

**Comment by atomoc** [comment]
@sergey-zabolotny
Создайте, пожалуйста, отдельный issue

**Comment by atomoc** [comment]
Проблему решил установкой libreelec)
