### ISSUE TITLE
chroot: can't execute '/system/bin/busybox': Exec format error

### ISSUE THREAD

**Issue by sergey-zabolotny** [sshmanko/acestream-armv7#9]
how to reproduce:

git clone git@github.com:sshmanko/acestream-armv7.git v3.1.33

add `set -xe` to the top and remove redirect to log file from last line from acestream.start file

create Dokerfile with:
```
FROM alpine:3.9
USER root

RUN set -ex; \
    apk add --update --no-cache \
	bash

COPY v3.1.33/ /opt/acestream/

EXPOSE 62062

CMD ["/opt/acestream/acestream.start"]
```

docker build -t acestream:3.1.33  .
start container with command:

docker run -d --privileged=true --name acestream-engine acestream:3.1.33
docker logs acestream-engine

**Comment by sergey-zabolotny** [comment]
правильно ли я понимаю - это надо запускать в докере на pi совместимых устройствах? т.е. на x86 это работать не будет?

**Comment by sshmanko** [comment]
there is already a docker image with acestream:
https://hub.docker.com/r/aaaler/acestream-pi/

This repository is tested on Raspberry PI 2/3 with latest Raspbian image.
I cannot help you with docker and alpine image unfortunately
